spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:G:\\Nasze\\Marcin\\JAVA\\todo-app\\todo-db'
  jpa:
    hibernate:
      ddl-auto: create
  main:
    banner-mode: off

task.template.allowMultipleTasks: false